apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: eslint
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to ESLint
      type: string
      default: "src/ tests/ --ext *.js"
  steps:
    - name: lint
      image: node:20-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Installing dependencies..."
        npm ci
        echo "Running ESLint..."
        npm run lint $(params.args)
